site_name: Spokane Python User Group
site_url: https://spokanepython.com/
site_description: Home of the Spokane Python User Group
repo_url: https://github.com/SpokaneTech/SpokanePythonUserGroup
repo_name: SpokanePythonUserGroup
edit_uri: blob/main/docs/

plugins:
  - social:
      cards_layout_options:
        font_family: Rubik
  - search
  - include-markdown

theme:
  name: material
  custom_dir: overrides
  logo: img/favicon.svg
  favicon: img/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - header.autohide
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/termynal.css

extra_javascript:
  - scripts/termynal.js

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - meta
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - "Home": "index.md"
  - "Meetups":
    - "f(s): Svelte": "meetups/svelte.md"
    - "Exploring Django's ORM": "meetups/exploring-django-orm.md"
    - "Lightning Talks II": "meetups/lightning-talks-2.md"
    - "Between Two Plants": "meetups/between-two-plants.md"
    - "Intro to HTMX": "meetups/intro-to-htmx.md"
    - "Intro to Dagger": "meetups/intro-to-dagger.md"
    - "Creating Python Rust bindings using PyO3": "meetups/rust-bindings.md"
    - "Spokane Tech: Kick Off": "meetups/spokane-tech-kick-off.md"
    - "Holiday Get Together": "meetups/holiday-get-together.md"
    - "Python Microframeworks": "meetups/python-microframeworks.md"
    - "DI, IoC, and You": "meetups/di-ioc-and-you.md"
    - "Python C Extensions": "meetups/c-extensions.md"
    - "Django 201": "meetups/django-201.md"
    - "Streamlit Deep Dive": "meetups/streamlit-deep-dive.md"
    - "Python Project Power-Up": "meetups/python-project-powerup.md"
    - "Getting Started with Django": "meetups/getting-started-with-django.md"
    - "MicroPyton & Embedded Hardware": "meetups/micropython-and-embedded-hardware.md"
    - "GitHub Actions and Robot Overlords": "meetups/github-actions-and-robot-overlords.md"
    - "An Evening of Lightning Talks": "meetups/an-evening-of-lightning-talks.md"
    - "Amazon Rekognition": "meetups/amazon-rekognition.md"
    - "Python Meets Radio": "meetups/python-meets-radio.md"
    - "Testing in Python": "meetups/testing-in-python.md"
    - "All Things Hosting": "meetups/all-things-hosting.md"
    - "Adventures in A.I.": "meetups/adventures-in-ai.md"
    - "Intro to Machine Learning": "meetups/intro-to-machine-learning.md"
    - "Journey to the Pythonic Peak": "meetups/pragmatic-python-02.md"
    - "Pragmatic Python": "meetups/pragmatic-python-01.md"
    - "Mk’ing spokanepython.com": "meetups/static-site-generation.md"
    - "Background Task Processing": "meetups/background-task-processing.md"
    - "Kubernetes and Python": "meetups/kubernetes.md"
    - "Typing for Fun and Profit": "meetups/typing-for-fun-and-profit.md"
    - "Getting Started with FastAPI": "meetups/getting-started-with-fastapi.md"
  - "Speak 📢": "speak.md"
  - "About": "about.md"
  - "Python Resources": "resources.md"

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pythonspokane
    - icon: fontawesome/brands/github
      link: https://github.com/python-spokane/
  analytics:
    provider: custom
    property: "spokanepython.com"
