site_name: Spokane Python User Group
site_url: https://spokanepython.com/
site_description: Home of the Spokane Python User Group
repo_url: https://github.com/Intellitect-Samples/SpokanePythonUserGroup
repo_name: SpokanePythonUserGroup
edit_uri: blob/main/docs/

plugins:
  - social:
      cards_font: Rubik
  - search

theme:
  name: material
  custom_dir: overrides
  logo: img/favicon.svg
  favicon: img/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/termynal.css

extra_javascript:
  - scripts/termynal.js

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - meta
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - "Home": "index.md"
  - "Meetups":
    - "GitHub Actions and Robot Overlords": "meetups/github-actions-and-robot-overlords.md"
    - "An Evening of Lightning Talks": "meetups/an-evening-of-lightning-talks.md"
    - "Amazon Rekognition": "meetups/amazon-rekognition.md"
    - "Python Meets Radio": "meetups/python-meets-radio.md"
    - "Testing in Python": "meetups/testing-in-python.md"
    - "All Things Hosting": "meetups/all-things-hosting.md"
    - "Adventures in A.I.": "meetups/adventures-in-ai.md"
    - "Intro to Machine Learning": "meetups/intro-to-machine-learning.md"
    - "Journey to the Pythonic Peak": "meetups/pragmatic-python-02.md"
    - "Pragmatic Python": "meetups/pragmatic-python-01.md"
    - "Mk’ing spokanepython.com": "meetups/static-site-generation.md"
    - "Background Task Processing": "meetups/background-task-processing.md"
    - "Kubernetes and Python": "meetups/kubernetes.md"
    - "Typing for Fun and Profit": "meetups/typing-for-fun-and-profit.md"
    - "Getting Started with FastAPI": "meetups/getting-started-with-fastapi.md"
  - "Speak 📢": "speak.md"
  - "About": "about.md"
  - "Python Resources": "resources.md"

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pythonspokane
    - icon: fontawesome/brands/github
      link: https://github.com/python-spokane/
  analytics:
    provider: custom
    property: "spokanepython.com"
